### ISSUE TITLE
Types or docs are wrong for getParametersByPath

### ISSUE THREAD

**Issue by iansu** [vandium-io/aws-param-store#10]
I was attempting to call `getParametersByPath` in a TypeScript project and it told me `path` needed to be an array. The docs indicate that it's a string though. I'm not sure if the types are wrong or the docs. I added a `@ts-ignore` comment to that line and passed a string and it seemed to work.

**Comment by richardhyatt** [comment]
Looks like the definition is incorrect - I don't maintain the TypeScript definitions for this library but would welcome a contribution.

**Comment by richardhyatt** [comment]
See #1
