### ISSUE TITLE
Any thoughts about also implementing PUT APIs ?

### ISSUE THREAD

**Issue by AvnerCohen** [vandium-io/aws-param-store#11]
If I want to a build a simple CLI on top of this, would be good for me to have the full get/put APIs:

https://docs.aws.amazon.com/cli/latest/reference/ssm/get-parameters-by-path.html

Thoughts?

**Comment by AvnerCohen** [comment]
Will you take a PR to add that?

**Comment by richardhyatt** [comment]
That would be great.

**Comment by AvnerCohen** [comment]
Closed with https://github.com/vandium-io/aws-param-store/pull/12
