### ISSUE TITLE
Timeout

### ISSUE THREAD

**Issue by robertoibarra** [vandium-io/aws-param-store#13]
Hi, I use the sample code and get a timeout after 3 seconds.

	exports.handler = (event, context, callback) => {
		console.log("running");
		let awsParamStore = require( 'aws-param-store' );

		try {
			let parameters = awsParamStore.getParametersSync( ['/folder/var'], { region: 'us-east-1' } );
			console.log( parameters );
		}
		catch( err ) {
			console.log( err );
		}

	}

I don't think it's a permissions or AWS config issue as the exact same lambda if I run this code it works:

	var AWS = require('aws-sdk');
	var ssm = new AWS.SSM();

	exports.handler = function(event, context) {    
		getParameterFromSystemManager(function(){
			console.log('done');
		context.done(null, 'Hello from Lambda');
		});
	
	};

	function getParameterFromSystemManager(callback) {
	
		// Fetches a parameter called REPO_NAME from SSM parameter store.
		// Requires a policy for SSM:GetParameter on the parameter being read.
		var params = {
			Name: '/folder/var',
			/* required */
			WithDecryption: /*true ||*/ false
		};
		console.log('in the getParameterFromSystemManager function')
		var request = ssm.getParameter(params, function(err, data) {
			if (err) console.log(err, err.stack); // an error occurred
			else console.log(data); // successful response
		
			callback();
		});

	}

**Comment by richardhyatt** [comment]
Is the timeout an exception or is it from the AWS Lambda environment?

**Comment by richardhyatt** [comment]
Closing the issue due to inactivity. If this is still an issue, we can reopen it.
