### ISSUE TITLE
npm install --production on consuming app missing aws-sdk

### ISSUE THREAD

**Issue by codeangler** [vandium-io/aws-param-store#15]
GIVEN that parent applicaiton has `aws-param-store` in their production dependencies 
WHEN running `npm install --production`  
THEN package requires `aws-sdk` 
AND actually it is not present.

proposed solution:  have `aws-sdk` as a dependency.

**Comment by richardhyatt** [comment]
Added `aws-sdk` as a peer dependency in the 3.1.0 release. It is this way because this library is used with AWS Lambda instances and the sdk is already part of the environment.
