### ISSUE TITLE
Doesn't work as expected

### ISSUE THREAD

**Issue by Mihailoff** [vandium-io/aws-param-store#3]
Have tried different combinations of recursive/decrypted/sync/async, nothing worked, no errors, empty response. 

aws-param-store 1.1.0
aws-sdk 2.202.0
node v8.8.1

Ended up using native aws sdk.
```
const AWS_SSM = require('aws-sdk/clients/ssm')

var ssm = new AWS_SSM({region: 'ca-central-1'})

ssm.getParameters({
  Names: [
    '/test',
  ]
}, function(err, data) {
  if (err) console.log(err, err.stack); // an error occurred
  else     console.log(data);           // successful response
})
```

**Comment by richardhyatt** [comment]
Can you post your code that doesn't work? Thanks

**Comment by Mihailoff** [comment]
It is pretty much as https://github.com/vandium-io/aws-param-store#getting-started

**Comment by richardhyatt** [comment]
ok - so if you add a `.catch(()` block like:

```js
const awsParamStore = require( 'aws-param-store' );

awsParamStore.newQuery( '/project1/service1/production', { region: 'us-east-1' } )
    .execute()
    .then( (parameters) => {

        // set env vars from here
    })
    .catch( (err) => {
         console.log( err );
    });
```

does it report an error? The `execute()` method returns a Promise that needs to get resolved to display a result or an error.  Let me know if this helps.

**Comment by richardhyatt** [comment]
Can we close this issue or would you like some help troubleshooting it?

**Comment by richardhyatt** [comment]
Closing issue - reopen if unresolved or further help is needed

**Comment by gtiongco95** [comment]
Also experiencing the same now, following the getting started in the npmjs site.

awsParamStore.getParametersByPath('/path/to/test', { region: 'ap-southeast-2' })
    .then((params) => {
        console.log(params);
    }).catch(console.error);

params is an empty array. There's no indication as to what is going wrong. How do I get this to work?
