### ISSUE TITLE
Query parameter by name

### ISSUE THREAD

**Issue by roribio** [vandium-io/aws-param-store#4]
Hi,

This is a feature request to add querying parameters by name instead of by path.

I looked at the code and played around with different calls but couldn't achieve the same functionality as `aws ssm get-parameters --name 'my-parameter'`.

I also played around with different libraries similar to this one and this is by far the best implementation I've tried, hence my decision to open an issue here.

Thanks,
Ronald

**Comment by richardhyatt** [comment]
Thanks for your kind words about this project.

I will work on adding the feature in the next day or so. How do you see yourself calling the API - should it be a switch or something a little more directed via code?

**Comment by roribio** [comment]
Hey @richardhyatt, thanks for your quick reply.

The AWS CLI provides `get-parameters` and `get-parameters-by-path` calls so, following a similar approach, I see a few of options:

1. Rename `newQuery` function to `getParameter` and add a `.byPath()` switch. This is probably the most involved and breaks backwards compatibility but could arguably be more readable and self-evident.
2. Keep everything the same and add a `.getParent()` switch.
3. Add `getParameter` as a new function.

Hope this helps 😄

**Comment by richardhyatt** [comment]
Probably option #3 - are you looking for async only or both async and sync?

**Comment by roribio** [comment]
I'm looking for sync specifically but I see the value in having both.

**Comment by richardhyatt** [comment]
Pushed a beta implementation to the 2.x branch and added some quick documentation to the readme.md

**Comment by roribio** [comment]
Looks good to me 💯 

I'm curious about why you dropped the `executeSync()` switch.

**Comment by richardhyatt** [comment]
Published in 2.0.0
