### ISSUE TITLE
GetParameters throws error when more than 10 parameters

### ISSUE THREAD

**Issue by broom9** [vandium-io/aws-param-store#9]
AWS returns an error with message "Member must have length less than or equal to 10"

**Comment by richardhyatt** [comment]
This limitation is [documented](https://docs.aws.amazon.com/systems-manager/latest/APIReference/API_GetParameters.html) by SSM.getParameters() in the AWS SDK.

In 4.0, I've Implemented logic to cycle through blocks of 10 parameters at a time, executing the SSM calls in sequence.
